import mysql.connector 

mydb = mysql.connector.connect(host="localhost",user="root",password="HiMysql123@",database="Inventory_Management")

cur = mydb.cursor()

#CRREATING A DATABASE 

db = "CREATE DATABASE Inventory_Management"

# CREATING A MANUFACTURE TABLE

cur.execute('''CREATE TABLE MANUFACTURE(
MANU_ID INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
MANU_ITEM VARCHAR(30) NOT NULL,
MANU_DATE DATE NOT NULL ,
STORES VARCHAR(30) NOT NULL,
NUM_PRODUCTS INT NOT NULL,
ITEMS_COLOR VARCHAR(25) NOT NULL,
DEF_ITEMS INT NOT NULL,
REQUIRED_ITEMS INT NOT NULL,
COMPANY VARCHAR(35)
);''')

# ASSIGNING THE AUTO_INCREMENT VALUE TO 101;

cur.execute("ALTER TABLE MANUFACTURE AUTO_INCREMENT = 101;")

# INSERTING THE DATA INTO THE TABLE MANUFACTURE 

qur =" INSERT INTO MANUFACTURE (MANU_ITEM,MANU_DATE,STORES,NUM_PRODUCTS,ITEMS_COLOR,DEF_ITEMS,REQUIRED_ITEMS,COMPANY) VALUES (%s,%s,%s,%s,%s,%s,%s,%s)"
val = [	 
	("WOODEN CHAIRS",'2019-03-20',"STRONG WOOD",15,"BROWN",2,20,"MECSTORES"),
	("WOODEN CHARIS",'2023-05-05',"LIGHT STORE",23,"DARK BROWN",1,33,"SUPER FIT"),
	("SHIRT",'2023-04-01',"ORay",250,"RED",2,500,"SILICON "),
	("TOYS",'2019-03-23',"MyKids",50,"RED",1,100,"CHILD COMFORT"),
	("WOODEN TABLE",'2023-03-04',"MyCare",25,"BROWN",1,50,"SS EXPORT"),
	("WOODEN CHAIR",'2019-04-22',"ABC",25,"BROWN",2,50,"XYZ"),
	("WOODEN CHAIR",'2019-03-27',"XYZ",20,"DARK BLACK",1,30,"WCX")
	]

cur.executemany(qur,val)

# CREATING GOODS TABLE 

cur.execute('''CREATE TABLE GOODS(
 GOODS_ID INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
 MANU_DATE DATE NOT NULL,
 MANUFACTURED_ITEMS VARCHAR(30) NOT NULL
 )''');

# ASSIGNING THE AUTO_INCREMENT VALUE TO 201;

cur.execute("ALTER TABLE GOODS AUTO_INCREMENT = 201;")

#  # INSERTING THE DATA INTO GOODS TABLE 

goods_ins = "INSERT INTO GOODS (MANU_DATE,MANUFACTURED_ITEMS) VALUES (%s,%s)"
goods_values = [
	('2019-03-20',"WOODEN CHAIRS"),
	('2023-04-01',"SHIRTS"),
	('2023-03-04',"TOYS"),
	('2019-03-23',"WOODEN TABLE"),
	('2023-03-04',"WOODEN TABLES"),
	('2019-03-20',"SHIRTS")
	]
cur.executemany(goods_ins,goods_values)

# CREATING PURCHASE TABLE 

cur.execute('''CREATE TABLE PURCHASE(
PURCHASE_ID INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
PURCHASE_AMT INT NOT NULL
)''')

 # ASSIGNING THE AUTO_INCREMENT VALUE TO 301;

cur.execute("ALTER TABLE GOODS AUTO_INCREMENT = 301;") 

# INSERTING DATA INTO PURCHASE TABLE 

pur_ins = cur.execute("INSERT INTO PURCHASE (PURCHASE_ID,PURCHASE_AMT) VALUES (%s,%s)")

pur_values = [
	(2000),
	(3000),
	(5000),
	(25000),
	(28000),
	(45000),
	(500000)
	]

cur.executemany(pur_ins,pur_values)

# CREATE TABLE SALE 

cur.execute('''CREATE TABLE SALE(
SOLD_DIFF_STORES VARCHAR(50) NOT NULL,
SALE_DATE DATE NOT NULL,
PROFIT_MARGIN INT NOT NULL,
TOTAL_AMT INT NOT NULL,
ITEM_NAME VARCHAR(50) NOT NULL
);''')

# INSRTING DATA INTO SALE TABLE 

sal_ins = "INSERT INTO SALE VALUES (%s,%s,%s,%s,%s)"
sal_values = [
	("ORay",'2023-09-23',100,200,"WOODEN TABLE"),
	("MyCare",'2019-01-23',23,150,"SHIRT"),
	("ABC",'2023-03-25',25,250,"TOYS"),
	("XYZ",'2023-04-22',10,100,"WOODEN TABLE"),
	("CYZ",'2019-03-04',250,500,"WOODEN CHARIS"),
	("ZYZ",'2018-05-15',18,75,"SHIRT")
	]
cur.executemany()

# query 1 

cur.execute("DELETE FROM MANUFACTURE WHERE MANU_ITEM="SHIRT" AND STORES="ORay" AND MANU_DATE="2023-04-01"")

# query 2 

cur.execute("UPDATE MANUFACTURE SET ITEMS_COLOR = "BLUE",STORES="BEST PRODUCT" WHERE ITEMS_COLOR = "RED" AND STORES="MyKids"")

# query 3 

cur.execute("SELECT MANU_ITEM FROM MANUFACTURE WHERE MANU_ITEM = "WOODEN CHAIR" AND MANU_DATE < '2023-05-01'")

# query 4

cur.execute('''SELECT SUM(PROFIT_MARGIN) AS PROFIT_MARGIN FROM SALE AS T1 INNER  JOIN MANUFACTURE AS T2 ON  
T1.ITEM_NAME = T2.MANU_ITEM''')

mydb.commit()





